### ISSUE TITLE
你好

### ISSUE THREAD

**Issue by SSZX866** [JohnnyWongC/TsForm#1]
你好我想了解一下怎么用那个worlddownloader谢谢

**Comment by JohnnyWoong** [comment]
这个不应该在那里问吗..我没记错的话只要放在mod文件夹下.然后登录服务器就会把你走的地方都下下来,只要服务器没有禁止这个功能

**Comment by SSZX866** [comment]
能交个朋友吗 我不太会用这个 Q2386316625
